//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotDossier.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EpicBattle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EpicBattle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotDossier.Resources.Strings.EpicBattle", typeof(EpicBattle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Reserves.
        /// </summary>
        public static string abilityInfo_manage_abilities {
            get {
                return ResourceManager.GetString("abilityInfo/manage_abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select available Combat Reserves..
        /// </summary>
        public static string abilityInfo_manage_abilities_desc {
            get {
                return ResourceManager.GetString("abilityInfo/manage_abilities_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombs.
        /// </summary>
        public static string abilityInfo_params_airstrike_bombsNumber {
            get {
                return ResourceManager.GetString("abilityInfo/params/airstrike/bombsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Area.
        /// </summary>
        public static string abilityInfo_params_airstrike_dropArea {
            get {
                return ResourceManager.GetString("abilityInfo/params/airstrike/dropArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stun.
        /// </summary>
        public static string abilityInfo_params_airstrike_stun {
            get {
                return ResourceManager.GetString("abilityInfo/params/airstrike/stun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact Area.
        /// </summary>
        public static string abilityInfo_params_artillery_areaRadius {
            get {
                return ResourceManager.GetString("abilityInfo/params/artillery/areaRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string abilityInfo_params_artillery_duration {
            get {
                return ResourceManager.GetString("abilityInfo/params/artillery/duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shells.
        /// </summary>
        public static string abilityInfo_params_artillery_shotsNumber {
            get {
                return ResourceManager.GetString("abilityInfo/params/artillery/shotsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooldown.
        /// </summary>
        public static string abilityInfo_params_common_cooldownTime {
            get {
                return ResourceManager.GetString("abilityInfo/params/common/cooldownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment.
        /// </summary>
        public static string abilityInfo_params_common_delay {
            get {
                return ResourceManager.GetString("abilityInfo/params/common/delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew Performance.
        /// </summary>
        public static string abilityInfo_params_inspire_crewIncreaseFactor {
            get {
                return ResourceManager.GetString("abilityInfo/params/inspire/crewIncreaseFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string abilityInfo_params_inspire_duration {
            get {
                return ResourceManager.GetString("abilityInfo/params/inspire/duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Down Time.
        /// </summary>
        public static string abilityInfo_params_inspire_inactivationDelay {
            get {
                return ResourceManager.GetString("abilityInfo/params/inspire/inactivationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Radius.
        /// </summary>
        public static string abilityInfo_params_inspire_radius {
            get {
                return ResourceManager.GetString("abilityInfo/params/inspire/radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Block Time.
        /// </summary>
        public static string abilityInfo_params_passive_engineering_captureBlockBonusTime {
            get {
                return ResourceManager.GetString("abilityInfo/params/passive_engineering/captureBlockBonusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Speed.
        /// </summary>
        public static string abilityInfo_params_passive_engineering_captureSpeedFactor {
            get {
                return ResourceManager.GetString("abilityInfo/params/passive_engineering/captureSpeedFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resupply Circle Refresh.
        /// </summary>
        public static string abilityInfo_params_passive_engineering_resupplyCooldownFactor {
            get {
                return ResourceManager.GetString("abilityInfo/params/passive_engineering/resupplyCooldownFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resupply Speed.
        /// </summary>
        public static string abilityInfo_params_passive_engineering_resupplyHealthPointsFactor {
            get {
                return ResourceManager.GetString("abilityInfo/params/passive_engineering/resupplyHealthPointsFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revealed Area.
        /// </summary>
        public static string abilityInfo_params_recon_revealedArea {
            get {
                return ResourceManager.GetString("abilityInfo/params/recon/revealedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300m x 750m.
        /// </summary>
        public static string abilityInfo_params_recon_revealedArea_value {
            get {
                return ResourceManager.GetString("abilityInfo/params/recon/revealedArea/value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotting Duration.
        /// </summary>
        public static string abilityInfo_params_recon_spottingDuration {
            get {
                return ResourceManager.GetString("abilityInfo/params/recon/spottingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke Grenades.
        /// </summary>
        public static string abilityInfo_params_smoke_projectilesNumber {
            get {
                return ResourceManager.GetString("abilityInfo/params/smoke/projectilesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Area (length, width).
        /// </summary>
        public static string abilityInfo_params_smoke_targetedArea {
            get {
                return ResourceManager.GetString("abilityInfo/params/smoke/targetedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke Lifetime.
        /// </summary>
        public static string abilityInfo_params_smoke_totalDuration {
            get {
                return ResourceManager.GetString("abilityInfo/params/smoke/totalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string abilityInfo_properties {
            get {
                return ResourceManager.GetString("abilityInfo/properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string abilityInfo_units_meter {
            get {
                return ResourceManager.GetString("abilityInfo/units/meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string abilityInfo_units_seconds {
            get {
                return ResourceManager.GetString("abilityInfo/units/seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance to Frontline.
        /// </summary>
        public static string advance_message_txt {
            get {
                return ResourceManager.GetString("advance_message_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance to Frontline.
        /// </summary>
        public static string advance_mission_txt {
            get {
                return ResourceManager.GetString("advance_mission_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bases captured.
        /// </summary>
        public static string after_battle_stats_bases_captured {
            get {
                return ResourceManager.GetString("after_battle_stats/bases_captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of own vehicles destroyed / recovered.
        /// </summary>
        public static string after_battle_stats_destroy_recover {
            get {
                return ResourceManager.GetString("after_battle_stats/destroy_recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones captured / objectives destroyed.
        /// </summary>
        public static string after_battle_stats_objectives_atk {
            get {
                return ResourceManager.GetString("after_battle_stats/objectives_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times defended.
        /// </summary>
        public static string after_battle_stats_objectives_def {
            get {
                return ResourceManager.GetString("after_battle_stats/objectives_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives destroyed.
        /// </summary>
        public static string after_battle_stats_objectives_destroyed {
            get {
                return ResourceManager.GetString("after_battle_stats/objectives_destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives reached.
        /// </summary>
        public static string after_battle_stats_objectives_reached {
            get {
                return ResourceManager.GetString("after_battle_stats/objectives_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Premium:.
        /// </summary>
        public static string after_battle_stats_with_premium {
            get {
                return ResourceManager.GetString("after_battle_stats/with_premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contested.
        /// </summary>
        public static string base_contested_atk {
            get {
                return ResourceManager.GetString("base/contested_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Attack.
        /// </summary>
        public static string base_contested_def {
            get {
                return ResourceManager.GetString("base/contested_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Armor.
        /// </summary>
        public static string battleResults_armor {
            get {
                return ResourceManager.GetString("battleResults/armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance.
        /// </summary>
        public static string battleResults_assistance {
            get {
                return ResourceManager.GetString("battleResults/assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Damage.
        /// </summary>
        public static string battleResults_crits {
            get {
                return ResourceManager.GetString("battleResults/crits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string battleResults_damage {
            get {
                return ResourceManager.GetString("battleResults/damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyed.
        /// </summary>
        public static string battleResults_kill {
            get {
                return ResourceManager.GetString("battleResults/kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotted.
        /// </summary>
        public static string battleResults_spotting {
            get {
                return ResourceManager.GetString("battleResults/spotting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture %(strArg1)s.
        /// </summary>
        public static string chat_shortcuts_attention_to_base_atk {
            get {
                return ResourceManager.GetString("chat_shortcuts/attention_to_base_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend %(strArg1)s.
        /// </summary>
        public static string chat_shortcuts_attention_to_base_def {
            get {
                return ResourceManager.GetString("chat_shortcuts/attention_to_base_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Objective %(int32Arg1)s.
        /// </summary>
        public static string chat_shortcuts_attention_to_objective_atk {
            get {
                return ResourceManager.GetString("chat_shortcuts/attention_to_objective_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend Objective %(int32Arg1)s.
        /// </summary>
        public static string chat_shortcuts_attention_to_objective_def {
            get {
                return ResourceManager.GetString("chat_shortcuts/attention_to_objective_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention to location!.
        /// </summary>
        public static string chat_shortcuts_attention_to_position {
            get {
                return ResourceManager.GetString("chat_shortcuts/attention_to_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string command_shortcut_title {
            get {
                return ResourceManager.GetString("command_shortcut/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front blockedplayer limit reached.
        /// </summary>
        public static string deploymentMap_lanePlayerLimitReached {
            get {
                return ResourceManager.GetString("deploymentMap/lanePlayerLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front blockedvehicle type limit reached.
        /// </summary>
        public static string deploymentMap_spgLimitReached {
            get {
                return ResourceManager.GetString("deploymentMap/spgLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave zone!.
        /// </summary>
        public static string destroy_timers_airstrike_txt {
            get {
                return ResourceManager.GetString("destroy_timers/airstrike_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Reserves.
        /// </summary>
        public static string epic_battle_meta_view_abilities {
            get {
                return ResourceManager.GetString("epic_battle_meta_view/abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire.
        /// </summary>
        public static string epic_battle_meta_view_Acquire_skill {
            get {
                return ResourceManager.GetString("epic_battle_meta_view/Acquire_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander Level.
        /// </summary>
        public static string epic_battle_meta_view_commander_level {
            get {
                return ResourceManager.GetString("epic_battle_meta_view/commander_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string epic_battle_meta_view_Max_skill {
            get {
                return ResourceManager.GetString("epic_battle_meta_view/Max_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieved Rank.
        /// </summary>
        public static string epic_battles_after_battle_Achieved_Rank {
            get {
                return ResourceManager.GetString("epic_battles_after_battle/Achieved_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Tier Reached.
        /// </summary>
        public static string epic_battles_after_battle_Level_Up_Max_Title {
            get {
                return ResourceManager.GetString("epic_battles_after_battle/Level_Up_Max_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tier Achieved.
        /// </summary>
        public static string epic_battles_after_battle_Level_Up_Title {
            get {
                return ResourceManager.GetString("epic_battles_after_battle/Level_Up_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string epic_battles_after_battle_Title {
            get {
                return ResourceManager.GetString("epic_battles_after_battle/Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Tier VIII vehicle for the Frontline mode..
        /// </summary>
        public static string epicBattlesCarousel_lockedTooltip_body {
            get {
                return ResourceManager.GetString("epicBattlesCarousel/lockedTooltip/body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Suitable.
        /// </summary>
        public static string epicBattlesCarousel_lockedTooltip_header {
            get {
                return ResourceManager.GetString("epicBattlesCarousel/lockedTooltip/header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONTLINE.
        /// </summary>
        public static string epicBattlesInfoView_battleModeTitle {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/battleModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier Progress.
        /// </summary>
        public static string epicBattlesInfoView_fameLabelHighlight {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/fameLabelHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the highest Tier.
        /// </summary>
        public static string epicBattlesInfoView_maxLevel {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/maxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string epicBattlesInfoView_maxMetaString {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/maxMetaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string epicBattlesInfoView_metaLevel {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/metaLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spend Supply Points to acquire unique and powerful Combat Reserves..
        /// </summary>
        public static string epicBattlesInfoView_panelDescription_abilities {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/panelDescription/abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform well in battle to get Ranks and increase your Tier..
        /// </summary>
        public static string epicBattlesInfoView_panelDescription_battlePerformance {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/panelDescription/battlePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn special rewards by resetting your Tier and your Combat Reserves..
        /// </summary>
        public static string epicBattlesInfoView_panelDescription_prestige {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/panelDescription/prestige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn an increasing amount of rewards until you reach Tier 30..
        /// </summary>
        public static string epicBattlesInfoView_panelDescription_rewards {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/panelDescription/rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMBAT RESERVES.
        /// </summary>
        public static string epicBattlesInfoView_panelTitle_abilities {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/panelTitle/abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIER PROGRESS.
        /// </summary>
        public static string epicBattlesInfoView_panelTitle_battlePerformance {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/panelTitle/battlePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESTIGE REWARDS.
        /// </summary>
        public static string epicBattlesInfoView_panelTitle_prestige {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/panelTitle/prestige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIER REWARDS.
        /// </summary>
        public static string epicBattlesInfoView_panelTitle_rewards {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/panelTitle/rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Introduction.
        /// </summary>
        public static string epicBattlesInfoView_ruleBattlePerformanceButton_label {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/ruleBattlePerformanceButton/label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Rewards.
        /// </summary>
        public static string epicBattlesInfoView_ruleRewardsButton_label {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/ruleRewardsButton/label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Rewards.
        /// </summary>
        public static string epicBattlesInfoView_ruleRewardsPrestigeButton_label {
            get {
                return ResourceManager.GetString("epicBattlesInfoView/ruleRewardsPrestigeButton/label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string epicBattlesPrestigeView_cancelButtonText {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/cancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string epicBattlesPrestigeView_congratulations {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In exchange you will get the following rewards:.
        /// </summary>
        public static string epicBattlesPrestigeView_exchange {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your Frontline progress.
        /// </summary>
        public static string epicBattlesPrestigeView_mainTitle {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/mainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will achieve: .
        /// </summary>
        public static string epicBattlesPrestigeView_prestigeInfo {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/prestigeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestige Level %(level)s.
        /// </summary>
        public static string epicBattlesPrestigeView_prestigeLevel {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/prestigeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your Combat Reserves and Supply Points will be removed..
        /// </summary>
        public static string epicBattlesPrestigeView_removeAbilities_desc {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/removeAbilities/desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Combat Reserves.
        /// </summary>
        public static string epicBattlesPrestigeView_removeAbilities_title {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/removeAbilities/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string epicBattlesPrestigeView_resetButtonText {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/resetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Frontline Tier will be reset to Tier 1..
        /// </summary>
        public static string epicBattlesPrestigeView_resetLevel_desc {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/resetLevel/desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Tier.
        /// </summary>
        public static string epicBattlesPrestigeView_resetLevel_title {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/resetLevel/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone!.
        /// </summary>
        public static string epicBattlesPrestigeView_warning {
            get {
                return ResourceManager.GetString("epicBattlesPrestigeView/warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier Progress.
        /// </summary>
        public static string epicBattlesWidgetTooltip_famePoints {
            get {
                return ResourceManager.GetString("epicBattlesWidgetTooltip/famePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase your Tier by fighting in Frontline battles.
        /// </summary>
        public static string epicBattlesWidgetTooltip_famePointsDescription {
            get {
                return ResourceManager.GetString("epicBattlesWidgetTooltip/famePointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the highest Tier. Reset your Tier to receive additional rewards..
        /// </summary>
        public static string epicBattlesWidgetTooltip_prestigeReached {
            get {
                return ResourceManager.GetString("epicBattlesWidgetTooltip/prestigeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undistributed players: %(total)s.
        /// </summary>
        public static string epictraining_info_otherLabel {
            get {
                return ResourceManager.GetString("epictraining/info/otherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attackers [%(lane1)s|%(lane2)s|%(lane3)s].
        /// </summary>
        public static string epictraining_info_team1LaneLabel {
            get {
                return ResourceManager.GetString("epictraining/info/team1LaneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defenders [%(lane1)s|%(lane2)s|%(lane3)s].
        /// </summary>
        public static string epictraining_info_team2LaneLabel {
            get {
                return ResourceManager.GetString("epictraining/info/team2LaneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Order.
        /// </summary>
        public static string fittingSelectPopover_ChangeOrder {
            get {
                return ResourceManager.GetString("fittingSelectPopover/ChangeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string fittingSelectPopover_RemoveButton {
            get {
                return ResourceManager.GetString("fittingSelectPopover/RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Reserves can be acquired through the Manage Reserves screen..
        /// </summary>
        public static string fittingSelectPopoverBattkeAbility_descText {
            get {
                return ResourceManager.GetString("fittingSelectPopoverBattkeAbility/descText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not acquired any Combat Reserves yet..
        /// </summary>
        public static string fittingSelectPopoverBattkeAbility_titleText {
            get {
                return ResourceManager.GetString("fittingSelectPopoverBattkeAbility/titleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All enemy vehicles destroyed.
        /// </summary>
        public static string game_all_enemies_defeated {
            get {
                return ResourceManager.GetString("game/all_enemies_defeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All objectives destroyed.
        /// </summary>
        public static string game_all_hqs_destroyed {
            get {
                return ResourceManager.GetString("game/all_hqs_destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All allied vehicles destroyed.
        /// </summary>
        public static string game_all_tanks_defeated {
            get {
                return ResourceManager.GetString("game/all_tanks_defeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat!.
        /// </summary>
        public static string game_defeat {
            get {
                return ResourceManager.GetString("game/defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw!.
        /// </summary>
        public static string game_draw {
            get {
                return ResourceManager.GetString("game/draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives have survived.
        /// </summary>
        public static string game_time_over {
            get {
                return ResourceManager.GetString("game/time_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        public static string game_victory {
            get {
                return ResourceManager.GetString("game/victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy objectives!.
        /// </summary>
        public static string global_msg_atk_focus_hq_short {
            get {
                return ResourceManager.GetString("global_msg/atk/focus_hq_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture a zone!.
        /// </summary>
        public static string global_msg_atk_time_short {
            get {
                return ResourceManager.GetString("global_msg/atk/time_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend objectives!.
        /// </summary>
        public static string global_msg_def_focus_hq_short {
            get {
                return ResourceManager.GetString("global_msg/def/focus_hq_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend the zones!.
        /// </summary>
        public static string global_msg_def_time_short {
            get {
                return ResourceManager.GetString("global_msg/def/time_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforce %(strArg1)s!.
        /// </summary>
        public static string global_msg_lane_center_short {
            get {
                return ResourceManager.GetString("global_msg/lane/center_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforce %(strArg1)s!.
        /// </summary>
        public static string global_msg_lane_east_short {
            get {
                return ResourceManager.GetString("global_msg/lane/east_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforce %(strArg1)s!.
        /// </summary>
        public static string global_msg_lane_west_short {
            get {
                return ResourceManager.GetString("global_msg/lane/west_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your tanks!.
        /// </summary>
        public static string global_msg_save_tanks_short {
            get {
                return ResourceManager.GetString("global_msg/save_tanks_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Area.
        /// </summary>
        public static string help_window_communication {
            get {
                return ResourceManager.GetString("help_window/communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only receive commands from allies who are in your visible minimap area or when the target of the command is in that area..
        /// </summary>
        public static string help_window_communication_description {
            get {
                return ResourceManager.GetString("help_window/communication/description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview Map.
        /// </summary>
        public static string help_window_overview_map {
            get {
                return ResourceManager.GetString("help_window/overview_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The overview map is used to get a tactical and strategic view of the whole battlefield. When the overview map is opened, the communication of the whole team can be received and messages can be sent..
        /// </summary>
        public static string help_window_overview_map_description {
            get {
                return ResourceManager.GetString("help_window/overview_map/description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        public static string help_window_recovery {
            get {
                return ResourceManager.GetString("help_window/recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery is introduced to self-destruct a vehicle that is stuck in the terrain. The mechanic is needed because increased battle duration and respawn possibility call for permanent engagement of the player..
        /// </summary>
        public static string help_window_recovery_description {
            get {
                return ResourceManager.GetString("help_window/recovery/description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Reserves.
        /// </summary>
        public static string help_window_reserves {
            get {
                return ResourceManager.GetString("help_window/reserves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every few minutes one vehicle is added to your reserve. The reserve can hold a maximum of two vehicles. When there are no vehicles left, you cannot deploy and need to wait until new vehicles are delivered..
        /// </summary>
        public static string help_window_reserves_description {
            get {
                return ResourceManager.GetString("help_window/reserves/description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached.
        /// </summary>
        public static string hq_under_attack_atk {
            get {
                return ResourceManager.GetString("hq/under_attack_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Attack.
        /// </summary>
        public static string hq_under_attack_def {
            get {
                return ResourceManager.GetString("hq/under_attack_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        public static string in_game_rank_experience_text {
            get {
                return ResourceManager.GetString("in_game_rank/experience_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired.
        /// </summary>
        public static string inspire_inspired {
            get {
                return ResourceManager.GetString("inspire/inspired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiring.
        /// </summary>
        public static string inspire_inspiring {
            get {
                return ResourceManager.GetString("inspire/inspiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        public static string lane_central_name {
            get {
                return ResourceManager.GetString("lane_central_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string lane_east_name {
            get {
                return ResourceManager.GetString("lane_east_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string lane_west_name {
            get {
                return ResourceManager.GetString("lane_west_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level %(lvl)s.
        /// </summary>
        public static string metaAbilityScreen_Ability_level {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Ability_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire is unavailable: You have no Supply Points..
        /// </summary>
        public static string metaAbilityScreen_Ability_locked {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Ability_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached maximum level for this Combat Reserve..
        /// </summary>
        public static string metaAbilityScreen_Ability_max_level {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Ability_max_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade is unavailable: You have no Supply Points..
        /// </summary>
        public static string metaAbilityScreen_Ability_not_points {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Ability_not_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not acquired.
        /// </summary>
        public static string metaAbilityScreen_Ability_not_unlocked {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Ability_not_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire.
        /// </summary>
        public static string metaAbilityScreen_Acquire_skill {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Acquire_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Supply Points by increasing your Frontline Tier..
        /// </summary>
        public static string metaAbilityScreen_get_skill_points {
            get {
                return ResourceManager.GetString("metaAbilityScreen/get_skill_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage reserves.
        /// </summary>
        public static string metaAbilityScreen_Manage_abilities {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Manage_abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE RESERVES.
        /// </summary>
        public static string metaAbilityScreen_Manage_reserves_header {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Manage_reserves_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspent Supply Points:.
        /// </summary>
        public static string metaAbilityScreen_Unspent_points {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Unspent_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string metaAbilityScreen_Upgrade_skill {
            get {
                return ResourceManager.GetString("metaAbilityScreen/Upgrade_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Objective.
        /// </summary>
        public static string mission_primary_title {
            get {
                return ResourceManager.GetString("mission/primary/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mission.
        /// </summary>
        public static string mission_title {
            get {
                return ResourceManager.GetString("mission/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone opens in: .
        /// </summary>
        public static string mission_zone_closing_atk {
            get {
                return ResourceManager.GetString("mission/zone_closing_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy bombardment in: .
        /// </summary>
        public static string mission_zone_closing_def {
            get {
                return ResourceManager.GetString("mission/zone_closing_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Zone.
        /// </summary>
        public static string missions_primary_atk_base {
            get {
                return ResourceManager.GetString("missions/primary/atk/base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy Objective.
        /// </summary>
        public static string missions_primary_atk_hq {
            get {
                return ResourceManager.GetString("missions/primary/atk/hq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(positiveOpen)s%(destroyed)s%(positiveClose)s of %(toDestroy)s.
        /// </summary>
        public static string missions_primary_atk_hq_additional_info {
            get {
                return ResourceManager.GetString("missions/primary/atk/hq_additional_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives destroyed:.
        /// </summary>
        public static string missions_primary_atk_hq_sub_title {
            get {
                return ResourceManager.GetString("missions/primary/atk/hq_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture zones to reach the main objectives. Destroy the main objectives..
        /// </summary>
        public static string missions_primary_atk_longdescription {
            get {
                return ResourceManager.GetString("missions/primary/atk/longdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend Zone.
        /// </summary>
        public static string missions_primary_def_base {
            get {
                return ResourceManager.GetString("missions/primary/def/base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend Objective.
        /// </summary>
        public static string missions_primary_def_hq {
            get {
                return ResourceManager.GetString("missions/primary/def/hq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(negativeOpen)s%(destroyed)s%(negativeClose)s of %(toDestroy)s.
        /// </summary>
        public static string missions_primary_def_hq_additional_info {
            get {
                return ResourceManager.GetString("missions/primary/def/hq_additional_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives lost:.
        /// </summary>
        public static string missions_primary_def_hq_sub_title {
            get {
                return ResourceManager.GetString("missions/primary/def/hq_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend the main objectives until the time runs out or destroy all attackers..
        /// </summary>
        public static string missions_primary_def_longdescription {
            get {
                return ResourceManager.GetString("missions/primary/def/longdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERTIME.
        /// </summary>
        public static string overtime_label {
            get {
                return ResourceManager.GetString("overtime/label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string primeTime_applyBtn {
            get {
                return ResourceManager.GetString("primeTime/applyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string primeTime_continueBtn {
            get {
                return ResourceManager.GetString("primeTime/continueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available servers: %(server)s.
        /// </summary>
        public static string primeTime_servers {
            get {
                return ResourceManager.GetString("primeTime/servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string primeTime_serverTooltip {
            get {
                return ResourceManager.GetString("primeTime/serverTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can switch to a Frontline server to continue pre-battle preparations..
        /// </summary>
        public static string primeTime_status_disable {
            get {
                return ResourceManager.GetString("primeTime/status/disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontline is currently unavailable on all servers..
        /// </summary>
        public static string primeTime_status_disableFirst {
            get {
                return ResourceManager.GetString("primeTime/status/disableFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On server %(server)s Frontline is available for: %(time)s..
        /// </summary>
        public static string primeTime_status_thisEnable {
            get {
                return ResourceManager.GetString("primeTime/status/thisEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONTLINE
        ///IS CURRENTLY UNAVAILABLE.
        /// </summary>
        public static string primeTime_title {
            get {
                return ResourceManager.GetString("primeTime/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME
        ///TO FRONTLINE.
        /// </summary>
        public static string primeTime_titleWelcome {
            get {
                return ResourceManager.GetString("primeTime/titleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceasefire is effective. It will end in %(time)s..
        /// </summary>
        public static string primeTimeAlertMessageBlock_message {
            get {
                return ResourceManager.GetString("primeTimeAlertMessageBlock/message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string progress_timers_active {
            get {
                return ResourceManager.GetString("progress_timers/active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base capture.
        /// </summary>
        public static string progress_timers_base_capture {
            get {
                return ResourceManager.GetString("progress_timers/base_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string progress_timers_blocked {
            get {
                return ResourceManager.GetString("progress_timers/blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base captured.
        /// </summary>
        public static string progress_timers_captured {
            get {
                return ResourceManager.GetString("progress_timers/captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully equipped.
        /// </summary>
        public static string progress_timers_fully_equipped {
            get {
                return ResourceManager.GetString("progress_timers/fully_equipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resupply point.
        /// </summary>
        public static string progress_timers_resupply {
            get {
                return ResourceManager.GetString("progress_timers/resupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string progress_timers_unavailable {
            get {
                return ResourceManager.GetString("progress_timers/unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string rank_no_name {
            get {
                return ResourceManager.GetString("rank/no_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promoted to %(rank)s.
        /// </summary>
        public static string rank_promotion {
            get {
                return ResourceManager.GetString("rank/promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string rank_rank0 {
            get {
                return ResourceManager.GetString("rank/rank0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergeant.
        /// </summary>
        public static string rank_rank1 {
            get {
                return ResourceManager.GetString("rank/rank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        public static string rank_rank2 {
            get {
                return ResourceManager.GetString("rank/rank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string rank_rank3 {
            get {
                return ResourceManager.GetString("rank/rank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string rank_rank4 {
            get {
                return ResourceManager.GetString("rank/rank4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string rank_rank5 {
            get {
                return ResourceManager.GetString("rank/rank5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily
        ///blocked.
        /// </summary>
        public static string recovery_Blocked {
            get {
                return ResourceManager.GetString("recovery/Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery unavailable.
        /// </summary>
        public static string recovery_disabled {
            get {
                return ResourceManager.GetString("recovery/disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press J
        ///to recover.
        /// </summary>
        public static string recovery_panel_base_text {
            get {
                return ResourceManager.GetString("recovery_panel/base_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move or shoot to cancel..
        /// </summary>
        public static string recovery_panel_recovery_cancel {
            get {
                return ResourceManager.GetString("recovery_panel/recovery_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery
        ///canceled.
        /// </summary>
        public static string recovery_panel_recovery_cancelled {
            get {
                return ResourceManager.GetString("recovery_panel/recovery_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery
        ///requested.
        /// </summary>
        public static string recovery_panel_recovery_requested {
            get {
                return ResourceManager.GetString("recovery_panel/recovery_requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture the next base.
        /// </summary>
        public static string reinforcement_capture_next_base_text {
            get {
                return ResourceManager.GetString("reinforcement/capture_next_base_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcements in .
        /// </summary>
        public static string reinforcement_reinforcement_in_text {
            get {
                return ResourceManager.GetString("reinforcement/reinforcement_in_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcements unavailable.
        /// </summary>
        public static string reinforcement_unavailable {
            get {
                return ResourceManager.GetString("reinforcement/unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string reinforcementsPanel_inText {
            get {
                return ResourceManager.GetString("reinforcementsPanel/inText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(seconds)s s until automatic deployment..
        /// </summary>
        public static string respawn_auto_timer_txt {
            get {
                return ResourceManager.GetString("respawn/auto_timer_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle!.
        /// </summary>
        public static string respawn_deploy_button {
            get {
                return ResourceManager.GetString("respawn/deploy_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium consumables cannot be purchased in a battle..
        /// </summary>
        public static string respawn_gold_ammo_not_available {
            get {
                return ResourceManager.GetString("respawn/gold_ammo_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string respawn_shop_title {
            get {
                return ResourceManager.GetString("respawn/shop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicles left.
        /// </summary>
        public static string respawn_tanks_left {
            get {
                return ResourceManager.GetString("respawn/tanks_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a front and vehicle to fight in.
        /// </summary>
        public static string respawnScreen_headerTitle {
            get {
                return ResourceManager.GetString("respawnScreen/headerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(seconds)s seconds.
        /// </summary>
        public static string respawnScreen_secondsTimerText {
            get {
                return ResourceManager.GetString("respawnScreen/secondsTimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreat.
        /// </summary>
        public static string retreat_message_txt {
            get {
                return ResourceManager.GetString("retreat_message_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreat to the next zone.
        /// </summary>
        public static string retreat_mission_txt {
            get {
                return ResourceManager.GetString("retreat_mission_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage 1.
        /// </summary>
        public static string scorePanel_stage1 {
            get {
                return ResourceManager.GetString("scorePanel/stage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage 2.
        /// </summary>
        public static string scorePanel_stage2 {
            get {
                return ResourceManager.GetString("scorePanel/stage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage 3.
        /// </summary>
        public static string scorePanel_stage3 {
            get {
                return ResourceManager.GetString("scorePanel/stage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue for Frontline is currently not open. You can still make changes to your loadout and manage Combat Reserves. You need a Tier VIII vehicle to participate in this game mode..
        /// </summary>
        public static string selectorTooltip_epicBattle_disabled_desc {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/disabled/desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event starts in:.
        /// </summary>
        public static string selectorTooltip_epicBattle_disabled_startIn {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/disabled/startIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event ends in:.
        /// </summary>
        public static string selectorTooltip_epicBattle_disabled_tillEnd {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/disabled/tillEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string selectorTooltip_epicBattle_disabled_timeTable_empty {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/disabled/timeTable/empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Schedule.
        /// </summary>
        public static string selectorTooltip_epicBattle_disabled_timeTable_title {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/disabled/timeTable/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string selectorTooltip_epicBattle_disabled_timeTable_today {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/disabled/timeTable/today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string selectorTooltip_epicBattle_disabled_timeTable_tomorrow {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/disabled/timeTable/tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode temporarily unavailable.
        /// </summary>
        public static string selectorTooltip_epicBattle_disabled_title {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/disabled/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer&apos;s performance is insufficient for this mode. You will experience issues with graphics and vehicle movement. Game client crashes are also probable..
        /// </summary>
        public static string selectorTooltip_epicBattle_enabled_attention_assuredLowPerformance {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/enabled/attention/assuredLowPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode demands high computer performance. In case of insufficient performance, try a lower graphics quality in Settings..
        /// </summary>
        public static string selectorTooltip_epicBattle_enabled_attention_informativeLowPerformance {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/enabled/attention/informativeLowPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode demands high computer performance. You will experience issues with map loading, graphics, and vehicle movement. In case of insufficient performance, try a lower graphics quality in Settings..
        /// </summary>
        public static string selectorTooltip_epicBattle_enabled_attention_possibleLowPerformance {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/enabled/attention/possibleLowPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle with automatic matching of allies against random enemies.
        /// Battle Type: Attack/Defense
        /// Player limit: 30
        /// Tier allowed: VIII.
        /// </summary>
        public static string selectorTooltip_epicBattle_enabled_body {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/enabled/body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontline.
        /// </summary>
        public static string selectorTooltip_epicBattle_enabled_header {
            get {
                return ResourceManager.GetString("selectorTooltip/epicBattle/enabled/header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In smoke.
        /// </summary>
        public static string smoke_In_smoke {
            get {
                return ResourceManager.GetString("smoke/In_smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectator Mode Camera.
        /// </summary>
        public static string spectator_mode_camera_controls_title {
            get {
                return ResourceManager.GetString("spectator_mode/camera_controls_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the camera with your mouse..
        /// </summary>
        public static string spectator_mode_camera_mouse_rotate {
            get {
                return ResourceManager.GetString("spectator_mode/camera_mouse_rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use W,A,S,D to move the camera around the map..
        /// </summary>
        public static string spectator_mode_camera_wasd {
            get {
                return ResourceManager.GetString("spectator_mode/camera_wasd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to start following..
        /// </summary>
        public static string spectator_mode_follow_text {
            get {
                return ResourceManager.GetString("spectator_mode/follow_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string spectator_mode_follow_title {
            get {
                return ResourceManager.GetString("spectator_mode/follow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next vehicle arrives in:.
        /// </summary>
        public static string spectator_mode_msg_text {
            get {
                return ResourceManager.GetString("spectator_mode/msg_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All vehicles destroyed!.
        /// </summary>
        public static string spectator_mode_msg_title {
            get {
                return ResourceManager.GetString("spectator_mode/msg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click again to stop following..
        /// </summary>
        public static string spectator_mode_unfollow_text {
            get {
                return ResourceManager.GetString("spectator_mode/unfollow_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop following.
        /// </summary>
        public static string spectator_mode_unfollow_title {
            get {
                return ResourceManager.GetString("spectator_mode/unfollow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(day)s d.
        /// </summary>
        public static string status_timeLeft_days {
            get {
                return ResourceManager.GetString("status/timeLeft/days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(hour)s h.
        /// </summary>
        public static string status_timeLeft_hours {
            get {
                return ResourceManager.GetString("status/timeLeft/hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a minute.
        /// </summary>
        public static string status_timeLeft_lessMin {
            get {
                return ResourceManager.GetString("status/timeLeft/lessMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(min)s min.
        /// </summary>
        public static string status_timeLeft_min {
            get {
                return ResourceManager.GetString("status/timeLeft/min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platoon.
        /// </summary>
        public static string super_platoon_panel_title {
            get {
                return ResourceManager.GetString("super_platoon_panel/title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fronts.
        /// </summary>
        public static string tab_screen_show_all_lanes {
            get {
                return ResourceManager.GetString("tab_screen/show_all_lanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My front.
        /// </summary>
        public static string tab_screen_show_my_lane {
            get {
                return ResourceManager.GetString("tab_screen/show_my_lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker.
        /// </summary>
        public static string team1Name {
            get {
                return ResourceManager.GetString("team1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string team2Name {
            get {
                return ResourceManager.GetString("team2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available in %(time)s..
        /// </summary>
        public static string tooltip_epicBattle_availableIn {
            get {
                return ResourceManager.GetString("tooltip/epicBattle/availableIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE RESERVES.
        /// </summary>
        public static string tutorial_hint_epicReservesBtnHint {
            get {
                return ResourceManager.GetString("tutorial/hint/epicReservesBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMBAT RESERVES.
        /// </summary>
        public static string tutorial_hint_epicReservesSlotHint {
            get {
                return ResourceManager.GetString("tutorial/hint/epicReservesSlotHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived!.
        /// </summary>
        public static string zone_arrived_text {
            get {
                return ResourceManager.GetString("zone/arrived_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string zone_capture_text {
            get {
                return ResourceManager.GetString("zone/capture_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured.
        /// </summary>
        public static string zone_captured_text {
            get {
                return ResourceManager.GetString("zone/captured_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend.
        /// </summary>
        public static string zone_defend_text {
            get {
                return ResourceManager.GetString("zone/defend_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy.
        /// </summary>
        public static string zone_destroy_text {
            get {
                return ResourceManager.GetString("zone/destroy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyed.
        /// </summary>
        public static string zone_destroyed_text {
            get {
                return ResourceManager.GetString("zone/destroyed_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy reinforcements.
        /// </summary>
        public static string zone_enemy_reinforced_text {
            get {
                return ResourceManager.GetString("zone/enemy_reinforced_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        public static string zone_headquarters_text {
            get {
                return ResourceManager.GetString("zone/headquarters_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Zone!.
        /// </summary>
        public static string zone_leave_zone {
            get {
                return ResourceManager.GetString("zone/leave_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string zone_lost_text {
            get {
                return ResourceManager.GetString("zone/lost_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string zone_reached_text {
            get {
                return ResourceManager.GetString("zone/reached_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy reinforcements:.
        /// </summary>
        public static string zone_reinforcement_timer_atk {
            get {
                return ResourceManager.GetString("zone/reinforcement_timer_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcements:.
        /// </summary>
        public static string zone_reinforcement_timer_def {
            get {
                return ResourceManager.GetString("zone/reinforcement_timer_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforcements.
        /// </summary>
        public static string zone_reinforcements_text {
            get {
                return ResourceManager.GetString("zone/reinforcements_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(minutes)s added.
        /// </summary>
        public static string zone_time_added {
            get {
                return ResourceManager.GetString("zone/time_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(minutes)s minutes remaining.
        /// </summary>
        public static string zone_time_left {
            get {
                return ResourceManager.GetString("zone/time_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string zone_zone_text {
            get {
                return ResourceManager.GetString("zone/zone_text", resourceCulture);
            }
        }
    }
}
